server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**
        - id: carts-service
          uri: lb://carts-service
          predicates:
            - Path=/api/carts/**